// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5O3KvHuxkc2ah2Pdo6XaAGuHxYgu4ZQI',
    appId: '1:574438658911:web:1ee8ee525790653ce51cea',
    messagingSenderId: '574438658911',
    projectId: 'aci-automation-21bb9',
    authDomain: 'aci-automation-21bb9.firebaseapp.com',
    storageBucket: 'aci-automation-21bb9.firebasestorage.app',
    measurementId: 'G-YG8B1GY9JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiP_YcxPWQ-PbwpICWni86ruNn2jB1C7w',
    appId: '1:574438658911:android:8c15d9722de7a41ee51cea',
    messagingSenderId: '574438658911',
    projectId: 'aci-automation-21bb9',
    storageBucket: 'aci-automation-21bb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6o5xx6rYomj_TNDbPv8zqpIDWlG2N_c',
    appId: '1:574438658911:ios:753da57304bee0bfe51cea',
    messagingSenderId: '574438658911',
    projectId: 'aci-automation-21bb9',
    storageBucket: 'aci-automation-21bb9.firebasestorage.app',
    iosBundleId: 'com.example.masterCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB6o5xx6rYomj_TNDbPv8zqpIDWlG2N_c',
    appId: '1:574438658911:ios:753da57304bee0bfe51cea',
    messagingSenderId: '574438658911',
    projectId: 'aci-automation-21bb9',
    storageBucket: 'aci-automation-21bb9.firebasestorage.app',
    iosBundleId: 'com.example.masterCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5O3KvHuxkc2ah2Pdo6XaAGuHxYgu4ZQI',
    appId: '1:574438658911:web:8eab504d19cce305e51cea',
    messagingSenderId: '574438658911',
    projectId: 'aci-automation-21bb9',
    authDomain: 'aci-automation-21bb9.firebaseapp.com',
    storageBucket: 'aci-automation-21bb9.firebasestorage.app',
    measurementId: 'G-6EGEEQGLFX',
  );

}